/**
 * Recorded LLM responses for the "See it in action" example document.
 *
 * Captured once from a real Gemini run at WEAK capability (free key, no paid
 * key) — the same capability a keyless first-run user evaluates at — so the
 * request hashes match on replay. When the user loads the example with no
 * working key, App switches the router to `mock` mode and installs these
 * recordings, so the pipeline replays the real responses (claims → ledger →
 * the planted Q2-vs-Q3 contradiction) with zero network calls. With a key
 * present, the live pipeline runs instead.
 *
 * These are captured real model outputs, not hand-authored fixtures. Regenerate
 * by loading the example in `record` mode at weak capability and dumping
 * `window.__sidecar__.dumpRecordings()`. Keyed by `reqHash` (see model/mock.ts).
 *
 * See docs/projects/onboarding_first_run.md § The example (keyless replay).
 */
export const EXAMPLE_DOC_RECORDING: Record<string, string> = {
  "r1l7h8i8_6539": "{\n  \"summary\": \"The document introduces Sidecar Review, a tool designed to provide feedback on document clarity and logic without modifying the original text.\",\n  \"claims\": [\n    {\n      \"text\": \"Sidecar Review is a companion panel that watches a working document and surfaces observations.\",\n      \"kind\": \"definition\"\n    },\n    {\n      \"text\": \"The goal is to sharpen the writer's own thinking, not to draft on their behalf.\",\n      \"kind\": \"commitment\"\n    }\n  ],\n  \"clarity_observations\": [],\n  \"unsupported_claim_observations\": [],\n  \"undefined_jargon_observations\": []\n}",
  "rxqkwnr_6342": "{\n  \"summary\": \"This section outlines the specific boundaries and exclusions for the assistant's operational scope.\",\n  \"claims\": [\n    {\n      \"text\": \"The assistant will not generate or rewrite document text in any phase.\",\n      \"kind\": \"constraint\"\n    }\n  ],\n  \"clarity_observations\": [],\n  \"unsupported_claim_observations\": [],\n  \"undefined_jargon_observations\": []\n}",
  "r10h0zfc_6476": "{\n  \"summary\": \"This section defines the success metrics for adoption and establishes the Q3 2026 launch timeline.\",\n  \"claims\": [\n    {\n      \"text\": \"We will measure adoption by weekly active documents and by the share of surfaced contradictions the author acts on.\",\n      \"kind\": \"commitment\"\n    },\n    {\n      \"text\": \"The public launch is firmly set for Q3 2026.\",\n      \"kind\": \"constraint\"\n    }\n  ],\n  \"clarity_observations\": [\n    {\n      \"text\": \"The metric for adoption lacks a target value or baseline to determine success.\",\n      \"substring\": \"measure adoption by weekly active documents and by the share of surfaced contradictions\"\n    }\n  ],\n  \"unsupported_claim_observations\": [],\n  \"undefined_jargon_observations\": []\n}",
  "r3ngf22_6400": "{\n  \"summary\": \"The project targets a public launch in Q2 2026, preceded by a six-week private beta and a four-week engineering effort for the core pipeline.\",\n  \"claims\": [\n    {\n      \"text\": \"We are committing to a public launch in Q2 2026\",\n      \"kind\": \"commitment\"\n    },\n    {\n      \"text\": \"private beta for design partners six weeks earlier\",\n      \"kind\": \"commitment\"\n    },\n    {\n      \"text\": \"Engineering has sized the core pipeline at four weeks\",\n      \"kind\": \"fact_claim\"\n    }\n  ],\n  \"clarity_observations\": [\n    {\n      \"text\": \"The Q2 2026 date lacks a specific target month or day, creating ambiguity for the six-week beta lead time.\",\n      \"substring\": \"Q2 2026\"\n    }\n  ],\n  \"unsupported_claim_observations\": [],\n  \"undefined_jargon_observations\": []\n}",
  "r3zf6lo_6487": "{\n  \"summary\": \"Product managers spend significant time manually reconciling inconsistencies in their own documentation due to limitations in current tooling.\",\n  \"claims\": [\n    {\n      \"text\": \"PMs spend nearly a third of every week hunting for inconsistencies in their own specs.\",\n      \"kind\": \"fact_claim\"\n    }\n  ],\n  \"clarity_observations\": [\n    {\n      \"text\": \"The phrase 'nearly a third' lacks a specific baseline or source for the time-tracking methodology.\",\n      \"substring\": \"nearly a third\"\n    }\n  ],\n  \"unsupported_claim_observations\": [\n    {\n      \"text\": \"The assertion that PMs spend nearly a third of their week reconciling documents is presented as a fact without providing the referenced internal research.\",\n      \"substring\": \"PMs spend nearly a third of every week hunting for inconsistencies in their own specs.\"\n    }\n  ],\n  \"undefined_jargon_observations\": []\n}",
  "r6paxqw_4104": "{\n  \"contradictions\": [\n    {\n      \"claimAId\": 6,\n      \"claimBId\": 7,\n      \"message\": \"Claim #6 sets the public launch for Q3 2026, while Claim #7 commits to a Q2 2026 launch.\"\n    }\n  ],\n  \"tensions\": [\n    {\n      \"claimAId\": 0,\n      \"claimBId\": 2,\n      \"message\": \"Claim #0 sizes the pipeline at four weeks, while Claim #2 requires a six-week acceleration of the beta timeline.\"\n    }\n  ]\n}",
  "r114ygbu_4643": "{\n  \"missing_topic_observations\": [\n    {\n      \"text\": \"The document lacks a technical architecture or integration strategy for how the tool monitors external documentation platforms.\"\n    }\n  ],\n  \"underexposed_topic_observations\": [\n    {\n      \"text\": \"The operational scope in \u00a74 provides no detail on how the tool handles sensitive or proprietary data within the documents it monitors.\"\n    }\n  ],\n  \"audience_mismatch_observations\": [],\n  \"structure_flow_observations\": [\n    {\n      \"text\": \"\u00a72 commits to a Q2 2026 launch, while \u00a75 commits to a Q3 2026 launch.\"\n    },\n    {\n      \"text\": \"The engineering effort described in \u00a72 is disconnected from the launch timeline in \u00a75.\"\n    }\n  ],\n  \"suggested_stage\": null\n}",
};
